name: Feature request triage bot

on:
  schedule:
    # Run at 14:00 every day
    - cron: '0 14 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@74b89a46292330ba949652680c30b0280249db74
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
