language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
  - CHANNEL=stable
  - KARMA_BROWSERS=DartiumWithWebPlatform
  - E2E_BROWSERS=Dartium
  - LOGS_DIR=/tmp/angular-build/logs

before_install:
- export DISPLAY=:99.0
- ./scripts/travis/install_dart.sh
- sh -e /etc/init.d/xvfb start
- if [[ -e SKIP_TRAVIS_TESTS ]]; then { cat SKIP_TRAVIS_TESTS ; exit 0; } fi
before_script:
- mkdir -p $LOGS_DIR
script:
- ./scripts/travis/build.sh
- ./scripts/travis/test_unit.sh
- ./scripts/travis/test_e2e.sh
after_script:
- ./scripts/travis/print-logs.sh
