name: material2
environment:
  sdk: '>=1.12.0-dev.5.10 <2.0.0'
dependencies:
  observe: '^0.13.1'
  angular2: '2.0.0-beta.0'
dev_dependencies:
  guinness: '^0.1.18'
  intl: '^0.12.4'
  unittest: '^0.11.5+4'
  quiver: '^0.21.4'
transformers:
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    entry_points:
        - lib/demo-app/demo-app.dart
