name: examples
environment:
  sdk: '>=1.10.0-dev.1.10 <2.0.0'
dependencies:
  angular2: '^2.0.0-alpha.31'
  browser: '^0.10.0'
dev_dependencies:
  guinness: '^0.1.17'
  test: '^0.12.3'
dependency_overrides:
  angular2:
    path: ../dist/dart/angular2

