name: angular2
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  analyzer: '>=0.22.4 <0.25.0'
  barback: '^0.15.2+2'
  code_transformers: '^0.2.5'
  dart_style: '^0.1.3'
  html: '^0.12.0'
  source_span: '^1.0.0'
  stack_trace: '^1.1.1'
transformers:
  - angular2
dev_dependencies:
  guinness: "^0.1.17"
