name: angular2
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  analyzer: '>=0.24.4 <0.27.0'
  barback: '^0.15.2+2'
  code_transformers: '^0.2.8'
  dart_style: '>=0.1.8 <0.3.0'
  glob: '^1.0.0'
  html: '^0.12.0'
  intl: '^0.12.4'
  logging: '>=0.9.0 <0.12.0'
  observe: '^0.13.1'
  protobuf: '^0.5.0'
  quiver: '^0.21.4'
  source_span: '^1.0.0'
  stack_trace: '^1.1.1'
dev_dependencies:
  guinness: '^0.1.18'
transformers:
- angular2
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
