name: angular2
version: <%= packageJson.version %>
authors:
<%= Object.keys(packageJson.contributors).map(function(name) {
  return '- '+name+' <'+packageJson.contributors[name]+'>';
}).join('\n') %>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: <%= packageJson.homepage %>
environment:
  sdk: '>=1.9.0-dev.8.0'
dependencies:
  analyzer: '^0.24.4'
  barback: '^0.15.2+2'
  code_transformers: '^0.2.5'
  dart_style: '^0.1.3'
  html: '^0.12.0'
  logging: '>=0.9.0 <0.11.0'
  source_span: '^1.0.0'
  stack_trace: '^1.1.1'
dev_dependencies:
  guinness: "^0.1.17"
transformers:
- angular2
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
