# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14.15.1-browsers

    working_directory: ~/repo

    environment:
      - CHROME_BIN: /usr/bin/google-chrome
      - CYPRESS_CACHE_FOLDER: /home/circleci/.cache/Cypress

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install
      - run: yarn cy:verify

      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.cache/Cypress
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: 'Run linting'
          command: yarn lint
      # run tests!
      - run:
          name: 'Run Unit tests'
          command: yarn test:ci

      - run:
          name: 'Run Cypress tests'
          command: yarn cy:ci
          no_output_timeout: '10m'

    artifacts:
      when: always
      paths:
        - cypress/videos/**/*.mp4
        - cypress/screenshots/**/*.png
      expire_in: 1 day
