# Configuration file for https://circleci.com/gh/angular/material2

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

var_1: &docker_image angular/ngcontainer:0.10.0
var_2: &cache_key v2-ng-mat-{{ checksum "WORKSPACE" }}-{{ checksum "yarn.lock" }}-0.7.0

# Settings common to each job
var_3: &job_defaults
  working_directory: ~/ng
  docker:
    - image: *docker_image

# Job step for checking out the source code from GitHub. This also ensures that the source code
# is rebased on top of master.
var_4: &checkout_code
  checkout:
    # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
    # which we want. See https://discuss.circleci.com/t/1662
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

# Restores the cache that could be available for the current Yarn lock file. The cache usually
# includes the node modules and the Bazel repository cache.
var_5: &restore_cache
  restore_cache:
    key: *cache_key

# Saves the cache for the current Yarn lock file. We store the node modules and the Bazel
# repository cache in order to make subsequent builds faster.
var_6: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - "node_modules"
      - "~/bazel_repository_cache"

# Decryption token that is used to decode the GCP credentials file in ".circleci/gcp_token".
var_7: &gcp_decrypt_token "angular"

# Job step that ensures that the node module dependencies are installed and up-to-date. We use
# Yarn with the frozen lockfile option in order to make sure that lock file and package.json are
# in sync. Unlike in Travis, we don't need to manually purge the node modules if stale because
# CircleCI automatically discards the cache if the checksum of the lock file has changed.
var_8: &yarn_install
  run: yarn install --frozen-lockfile --non-interactive

# Copies the Bazel config which is specifically for CircleCI to a location where Bazel picks it
# up and merges it with the project-wide bazel configuration (tools/bazel.rc)
var_9: &copy_bazel_config
  # Set up the CircleCI specific bazel configuration.
  run: sudo cp ./.circleci/bazel.rc /etc/bazel.bazelrc

# Sets up a different Docker image that includes a moe recent Firefox version which
# is needed for headless testing.
var_10: &docker-firefox-image
  # TODO(devversion): Temporarily use a image that includes Firefox 62 because the
  # ngcontainer image does include an old Firefox version that does not support headless.
  - image: circleci/node:11.4.0-browsers

# Attaches the release output which has been stored in the workspace to the current job.
# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
var_11: &attach_release_output
  attach_workspace:
    at: dist/

# Branch filter that we can specify for jobs that should only run on publish branches. This filter
# is used to ensure that not all upstream branches will be published as Github builds
# (e.g. revert branches, feature branches)
var_12: &publish_branches_filter
  branches:
    only:
      - master
      # 6.0.x, 7.1.x, etc.
      - /\d+\.\d+\.x/
      # 6.x, 7.x, 8.x etc
      - /\d+\.x/

# Branch filter that is usually applied to all jobs. Since there is no way within CircleCI to
# exclude a branch for all defined jobs, we need to manually specify the filters for each job.
# In order to reduce duplication we use a YAML anchor that just always excludes the "_presubmit"
# branch. We don't want to run Circle for the temporary "_presubmit" branch which is reserved
# for the caretaker.
var_13: &ignore_presubmit_branch_filter
  branches:
    ignore:
      - "_presubmit"
      - "ivy-2019"

# Runs a script that sets up the Bazel remote execution. This will be used by jobs that run
# Bazel primarily and should benefit from remote caching and execution.
var_14: &setup_bazel_remote_execution
  run:
    name: "Setup bazel RBE remote execution"
    command: ./scripts/circleci/bazel/setup-remote-execution.sh

# -----------------------------
# Container version of CircleCI
# -----------------------------
version: 2

# -----------------------------------------------------------------------------------------
# Job definitions. Jobs which are defined just here, will not run automatically. Each job
# must be part of a workflow definition in order to run for PRs and push builds.
# -----------------------------------------------------------------------------------------
jobs:

  # -----------------------------------
  # Build and test job that uses Bazel.
  # -----------------------------------
  bazel_build_test:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      GCP_DECRYPT_TOKEN: *gcp_decrypt_token
    steps:
      - *checkout_code
      - *restore_cache
      - *copy_bazel_config
      - *setup_bazel_remote_execution

      - run: bazel build src/... --build_tag_filters=-docs-package
      - run: bazel test src/... --build_tag_filters=-docs-package

      # Note: We want to save the cache in this job because the workspace cache also
      # includes the Bazel repository cache that will be updated in this job.
      - *save_cache

  # --------------------------------------------------------------------------------------------
  # Job that runs ts-api-guardian against our API goldens in "tools/public_api_guard".
  # This job fails whenever an API has been updated but not explicitly approved through goldens.
  # --------------------------------------------------------------------------------------------
  api_golden_checks:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      GCP_DECRYPT_TOKEN: *gcp_decrypt_token
    steps:
    - *checkout_code
    - *restore_cache
    - *copy_bazel_config
    - *setup_bazel_remote_execution

    - run: bazel test tools/public_api_guard/...

  # -----------------------------------------------------------------
  # Job that runs the e2e tests with Protractor and Chromium headless
  # -----------------------------------------------------------------
  e2e_tests:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      GCP_DECRYPT_TOKEN: *gcp_decrypt_token
    steps:
      - *checkout_code
      - *restore_cache
      - *copy_bazel_config
      - *setup_bazel_remote_execution

      - run: bazel test e2e/...

  # ------------------------------------------------------------------------------------------
  # Job that runs the unit tests on locally installed browsers (Chrome and Firefox headless).
  # The available browsers are installed through the angular/ngcontainer Docker image.
  # ------------------------------------------------------------------------------------------
  tests_local_browsers:
    docker: *docker-firefox-image
    resource_class: xlarge
    steps:
    - *checkout_code
    - *restore_cache
    - *yarn_install

    - run: ./scripts/circleci/run-local-browser-tests.sh

  # ----------------------------------------------------------------------------
  # Job that runs the unit tests on Browserstack. The browsers that will be used
  # to run the unit tests on Browserstack are set in: test/browser-providers.js
  # ----------------------------------------------------------------------------
  tests_browserstack:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      BROWSER_STACK_USERNAME: "angularteam1"
      BROWSER_STACK_ACCESS_KEY: "CaXMeMHD9pr5PHg8N7Jq"
    steps:
      - *checkout_code
      - *restore_cache
      - *yarn_install

      - run: ./scripts/circleci/run-browserstack-tests.sh

  # ----------------------------------------------------------------------------
  # Job that runs the unit tests on Saucelabs. The browsers that will be used
  # to run the unit tests on Saucelabs are set in: test/browser-providers.js
  # ----------------------------------------------------------------------------
  tests_saucelabs:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      SAUCE_USERNAME: "angular-ci"
      SAUCE_ACCESS_KEY: "9b988f434ff8-fbca-8aa4-4ae3-35442987"
      # Note: This number should not be too high because otherwise we might run into
      # a rate limit exception.
      KARMA_PARALLEL_BROWSERS: 2
    steps:
    - *checkout_code
    - *restore_cache
    - *yarn_install

    - run: ./scripts/circleci/run-saucelabs-tests.sh

  # -----------------------------------------------------------------------------------------
  # Job that builds the dev-app with AOT. In order to speed up this job, the release output
  # from the workspace storage will be attached to this job.
  # -----------------------------------------------------------------------------------------
  build_devapp_aot:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - *yarn_install
      - *attach_release_output

      - run: yarn gulp ci:aot

  # -------------------------------------------------------------------------
  # Job that pre-render's the universal app with `@angular/platform-server`.
  # This verifies that Angular Material can be rendered within Node.
  # -------------------------------------------------------------------------
  prerender_build:
    <<: *job_defaults
    steps:
    - *checkout_code
    - *restore_cache
    - *yarn_install

    - run: yarn gulp ci:prerender

  # ----------------------------------
  # Lint job. Runs the gulp lint task.
  # ----------------------------------
  lint:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - *yarn_install

      - run: yarn gulp ci:lint

  # -------------------------------------------------------------------------------------------
  # Job that builds all release packages with Gulp. The built packages can be then used in the
  # same workflow to publish snapshot builds or test the dev-app with the release packages.
  # -------------------------------------------------------------------------------------------
  build_release_packages:
    <<: *job_defaults
    resource_class: xlarge
    steps:
      - *checkout_code
      - *restore_cache
      - *yarn_install

      - run: yarn gulp ci:build-release-packages
      - run: yarn check-release-output

      # Store the release output in the workspace storage. This means that other jobs
      # in the same workflow can attach the release output to their job.
      - persist_to_workspace:
          root: dist
          paths:
            - "releases/**/*"

      # Since there is no UMD bundle that includes everything from the CDK, we need to move
      # all bundles into a directory. This allows us to store all CDK UMD bundles as job
      # artifacts that can be picked up by the Angular Github bot.
      - run:
          name: Prepare CDK artifacts for publish.
          command: |
            mkdir -p /tmp/cdk-umd-minified-bundles
            cp dist/releases/cdk/bundles/*.umd.min.js /tmp/cdk-umd-minified-bundles

      # Publish bundle artifacts which will be used to calculate the size change.
      # Note: Make sure that the size plugin from the Angular robot fetches the artifacts
      # from this CircleCI job (see .github/angular-robot.yml). Additionally any artifacts need to
      # be stored with the following path format: "{projectName}/{context}/{fileName}"
      # This format is necessary because otherwise the bot is not able to pick up the
      # artifacts from CircleCI. See:
      # https://github.com/angular/github-robot/blob/master/functions/src/plugins/size.ts#L392-L394
      - store_artifacts:
          path: dist/releases/material/bundles/material.umd.min.js
          destination: /angular_material/material_release_output/material.umd.min.js
      - store_artifacts:
          path: /tmp/cdk-umd-minified-bundles
          destination: /angular_material/cdk_release_output/

  # ----------------------------------------
  # Job that publishes the build snapshots
  # ----------------------------------------
  publish_snapshots:
    <<: *job_defaults
    resource_class: xlarge
    environment:
      GCP_DECRYPT_TOKEN: *gcp_decrypt_token
    steps:
      - *checkout_code
      - *restore_cache
      - *attach_release_output
      - *copy_bazel_config
      - *setup_bazel_remote_execution

      # CircleCI has a config setting to enforce SSH for all github connections.
      # This is not compatible with our mechanism of using a Personal Access Token
      # to publish the build snapshots. In order to fix this, we unset the global option.
      - run: git config --global --unset "url.ssh://git@github.com.insteadof"

      # TODO(devversion): Ideally the "build_release_packages" job should build all packages with
      # Bazel, but for now we mix up the Gulp and bazel setup, so we need to build the package here.
      - run: bazel build src/material-examples:npm_package --config=release

      - run: ./scripts/circleci/publish-snapshots.sh


  # ----------------------------------------------------------------------------
  # Job that runs the local browser tests against the Angular Github snapshots
  # ----------------------------------------------------------------------------
  snapshot_tests_local_browsers:
    docker: *docker-firefox-image
    resource_class: xlarge
    steps:
    - *checkout_code
    - *restore_cache
    - *yarn_install

    - run: node ./scripts/circleci/setup-angular-snapshots.js
    - run: ./scripts/circleci/run-local-browser-tests.sh

# ----------------------------------------------------------------------------------------
# Workflow definitions. A workflow usually groups multiple jobs together. This is useful if
# one job depends on another.
#
# NOTE: When updating this configuration section, make sure to update GitHub robot
#       config to match the new workflow jobs.
# ----------------------------------------------------------------------------------------
workflows:
  version: 2

  bazel_targets:
    jobs:
      - bazel_build_test:
          filters: *ignore_presubmit_branch_filter
      - api_golden_checks:
          filters: *ignore_presubmit_branch_filter

  unit_tests:
    jobs:
      - tests_local_browsers:
          filters: *ignore_presubmit_branch_filter
      - tests_browserstack:
          filters: *ignore_presubmit_branch_filter
      - tests_saucelabs:
          filters: *ignore_presubmit_branch_filter

  integration_tests:
    jobs:
      # Temporarily disable e2e tests until https://github.com/angular/angular/issues/29123
      # is resolved.
      # - e2e_tests:
      #     filters: *ignore_presubmit_branch_filter
      - prerender_build:
          filters: *ignore_presubmit_branch_filter

  release_output:
    jobs:
      - build_release_packages:
          filters: *ignore_presubmit_branch_filter
      - build_devapp_aot:
          filters: *ignore_presubmit_branch_filter
          requires:
            - build_release_packages
      - publish_snapshots:
          filters: *publish_branches_filter
          requires:
            - build_release_packages

  # Lint workflow. As we want to lint in one job, this is a workflow with just one job.
  lint:
    jobs:
      - lint:
          filters: *ignore_presubmit_branch_filter

  # Snapshot tests workflow that is scheduled to run all specified jobs at midnight everyday.
  # This workflow runs various jobs against the Angular snapshot builds from Github.
  snapshot_tests:
    jobs:
      # Note that we need additional jobs for the nightly snapshot tests because there is no
      # easy way to detect whether a job runs inside of a cronjob or specific workflow.
      # See: https://circleci.com/ideas/?idea=CCI-I-295
      - snapshot_tests_local_browsers
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                # We only want to run the "master" branch against the snapshot builds because
                # it's not guaranteed that older versions of Angular Material always work
                # with the latest Angular version.
                - master
