name: benchmarks_external
environment:
  sdk: '>=1.4.0'
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  angular2:
    path: ../angular2
transformers:
- angular:
    $exclude: "web/e2e_test"
    html_files:
      - web/src/naive_infinite_scroll/scroll_area.html
      - web/src/naive_infinite_scroll/scroll_item.html
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
