name: examples
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  observe: '^0.13.1'
  angular2: '^<%= packageJson.version %>'
  angular2_material: '^<%= packageJson.version %>'
  browser: '^0.10.0'
dev_dependencies:
  guinness: '^0.1.17'
  benchpress:
    path: ../benchpress
dependency_overrides:
  angular2:
    path: ../angular2
  angular2_material:
    path: ../angular2_material
transformers:
- angular2:
    $exclude:
    # The build currently fails on material files because there is not yet
    # support for transforming cross-package urls. (see issue #2982)
    - 'web/src/material/**'
    - 'web/src/zippy_component/**'
    # No need to transform the dart:mirrors specific entrypoints
    - '**/index_dynamic.dart'
    entry_points:
        - web/src/gestures/index.dart
        - web/src/hello_world/index.dart
        - web/src/key_events/index.dart
        - web/src/sourcemap/index.dart
        - web/src/todo/index.dart
        - web/src/order_management/index.dart
        - web/src/model_driven_forms/index.dart
        - web/src/observable_models/index.dart
        - web/src/person_management/index.dart
        - web/src/template_driven_forms/index.dart
        # These entrypoints are disabled until cross-package urls are working (issue #2982)
        # - web/src/material/button/index.dart
        # - web/src/material/checkbox/index.dart
        # - web/src/material/dialog/index.dart
        # - web/src/material/grid_list/index.dart
        # - web/src/material/input/index.dart
        # - web/src/material/progress-linear/index.dart
        # - web/src/material/radio/index.dart
        # - web/src/material/switcher/index.dart
        # - web/src/zippy_component/index.dart
        #
        # This entrypoint is not needed:
        # - web/src/material/demo_common.dart
    reflection_entry_points:
        - web/src/gestures/index.dart
        - web/src/hello_world/index.dart
        - web/src/key_events/index.dart
        - web/src/sourcemap/index.dart
        - web/src/todo/index.dart
        - web/src/model_driven_forms/index.dart
        - web/src/observable_models/index.dart
        - web/src/order_management/index.dart
        - web/src/person_management/index.dart
        - web/src/template_driven_forms/index.dart
        # These entrypoints are disabled until cross-package urls are working (issue #2982)
        # - web/src/material/button/index.dart
        # - web/src/material/checkbox/index.dart
        # - web/src/material/dialog/index.dart
        # - web/src/material/grid_list/index.dart
        # - web/src/material/input/index.dart
        # - web/src/material/progress-linear/index.dart
        # - web/src/material/radio/index.dart
        # - web/src/material/switcher/index.dart
        # - web/src/zippy_component/index.dart
        #
        # This entrypoint is not needed:
        # - web/src/material/demo_common.dart

- $dart2js:
    minify: false
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
    # Uncomment to generate summaries from dart2js
    # - --dump-info
