name: DevInfra

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  assistant_to_the_branch_manager:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - uses: angular/dev-infra/github-actions/branch-manager@6084f3b53ed4a84d48047eaad984e7dd6a081c90
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
