name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@bbf452beece35aac7c2fb844c7fc1bebf684fef8
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
  post_approval_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: angular/dev-infra/github-actions/post-approval-changes@bbf452beece35aac7c2fb844c7fc1bebf684fef8
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
