name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579  # renovate: tag=v2.0.0
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@2e2d1a6beeb26b0cc61c70f157f1dc073cdcf235
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
