name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, reopened]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  pull_request_labels:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: angular/dev-infra/github-actions/pull-request-labeling@ecf3adcf1cb85a0ecd32a3b5a1712ce946aa798a
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          labels: '{"requires: TGP": ["packages/core/primitives/**/{*,.*}"]}'
  post_approval_changes:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: angular/dev-infra/github-actions/post-approval-changes@ecf3adcf1cb85a0ecd32a3b5a1712ce946aa798a
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
  issue_labels:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/issue-labeling@ecf3adcf1cb85a0ecd32a3b5a1712ce946aa798a
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          google-generative-ai-key: ${{ secrets.GOOGLE_GENERATIVE_AI_KEY }}
