name: Feature request triage bot

on:
  schedule:
    # Run at 15:00 every day
    - cron: '0 15 * * *'

jobs:
  feature_triage:
    if: github.repository == 'angular/components'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/feature-request@4807c9f7b80d7a88cd045d88263c0aaf1296aeed
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
