name: 'Dependency Generation CSV'

on:

workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
  steps:
  - name: Generate Dependencies Action
    uses: thedave42/generate-dependencies-csv-action@v6
    with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      org-name: customer-success-architects
      depth: 4
      repo-names: angular
