name: Google Internal Tests Enforcement

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  trigger:
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: angular/dev-infra/github-actions/google-internal-tests@2ba53026d5358458a479227fee8c3d6d5c1e1dad
        with:
          run-tests-guide-url: http://go/angular-g3sync-start
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-config: ./.ng-dev/google-sync-config.json
