name: Google Internal Tests Enforcement

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  trigger:
    permissions:
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: angular/dev-infra/github-actions/google-internal-tests@5774b71c01a55c4c998f858ee37d3b77ae704c31
        with:
          run-tests-guide-url: http://go/angular-g3sync-start
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sync-config: ./.ng-dev/google-sync-config.json
