name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@f5e706a8bd255a86681369fabf0b8ebed4858b30
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
