name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@2a04da0754b050fb17d6cfc4a4b4fa8b5575ea86
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
