name: Lock Inactive Issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@66462f6
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
