name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@b5e4e3227f855adf65529353b73669718bcb8a12
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
