name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@a4fd924
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
