# Update the `events.json` file that powers the [AIO events page](https://angular.io/events) (if
# necessary) and create a pull request.
#
# For more details on the overall process, see
# [aio/scripts/generate-events/README.md](../../aio/scripts/generate-events/README.md).

name: Update AIO events

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # Run every day at 15:00.
    - cron: '0 15 * * *'

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  update_events:
    name: Update `events.json` (if necessary)
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          # Setting `persist-credentials: false` prevents the github-action account from being the
          # account that is attempted to be used for authentication, instead the remote is set to
          # an authenticated URL.
          persist-credentials: false
      - name: Install AIO dependencies
        run: yarn --cwd=aio install
      - name: Generate `events.json`
        run: node aio/scripts/generate-events/index.mjs --ignore-invalid-dates
      - name: Create a PR (if necessary)
        uses: angular/dev-infra/github-actions/create-pr-for-changes@96fdaaa056f1cfa7ffbc4c69b7e9007279f76c94
        with:
          branch-prefix: docs-update-events
          pr-title: 'docs: update events'
          pr-description: |
            Generated `events.json` with the latest events retrieved from the Firebase DB.
          pr-labels: |
            action: review
            area: docs
            target: patch
          angular-robot-token: ${{ secrets.ANGULAR_ROBOT_ACCESS_TOKEN }}
